title: Brianna Lea CEAMLS SAIRI Website Summer 2024 
logo: briannaxlea headshot.jpg
description: Hi! My name is Brianna Lea and this is my CEAMLS SAIRI Website for Summer 2024.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
